# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: HashBolt
site_url: https://lonero.org/
site_author: Andrew Kamal
site_description: >-
  Hashbolt is cryptographic hashing created for the next generation of blockchains

# Repository
repo_name: lonero-team/hashbolt
repo_url: https://github.com/Lonero-Team/hashbolt
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2018 - 2021 Andrew Kamal

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    scheme: slate
    primary: black
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        extensions/admonition.md: reference/admonitions.md
        extensions/codehilite.md: reference/code-blocks.md
        extensions/footnotes.md: reference/footnotes.md
        extensions/metadata.md: reference/meta-tags.md
        extensions/permalinks.md: setup/setting-up-navigation.md #permalink
        extensions/pymdown.md: reference/admonitions.md
        plugins/revision-date.md: setup/adding-a-git-repository.md #revision-date
        plugins/search.md: setup/setting-up-site-search.md
        releases/4.md: upgrading.md #upgrading-from-4x-to-5x
        releases/5.md: upgrading.md #upgrading-from-3x-to-4x
        releases/changelog.md: changelog.md
        setup/adding-social-links.md: setup/setting-up-the-footer.md
        sponsorship.md: insiders.md
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lonero-Team
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/squidfunk/mkdocs-material
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LoneroLNR
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/squidfunk/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/squidfunk

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Intro: intro.md
  - Abstract:
    - About: about.md
    - Premise: premise.md
    - Abstract: abstract.md
    - Introduction: customization.md
#    - Troubleshooting: troubleshooting.md
#    - Data privacy: data-privacy.md
#    - Insiders: insiders.md
#    - License: license.md
  - Mathematics:
    - Intro: setup/changing-the-colors.md
    - Proofs: setup/changing-the-fonts.md
    - Concepts: setup/changing-the-language.md
    - The Logic: setup/changing-the-logo-and-icons.md
    - Euclidean Geometry: setup/setting-up-navigation.md
    - Understanding Schemes: setup/setting-up-site-search.md
    - Considering Some Variables: setup/setting-up-site-analytics.md
#    - Setting up versioning: setup/setting-up-versioning.md
#    - Setting up the header: setup/setting-up-the-header.md
#    - Setting up the footer: setup/setting-up-the-footer.md
#    - Adding a git repository: setup/adding-a-git-repository.md
#    - Adding a comment system: setup/adding-a-comment-system.md
  - Cryptography:
    - P2P: reference/abbreviations.md
    - Hashing: reference/admonitions.md
    - Ring Signatures: reference/buttons.md
    - Masternodes and Consensus: reference/code-blocks.md
    - Encryption and Cryptography Schemes: reference/content-tabs.md
    - Data Integration, Theory and Hashgraphs: reference/data-tables.md
#    - Diagrams: reference/diagrams.md
#    - Footnotes: reference/footnotes.md
#    - Formatting: reference/formatting.md
#    - Icons + Emojis: reference/icons-emojis.md
#    - Images: reference/images.md
#    - Lists: reference/lists.md
    - Software Defined Networking Integrations: reference/mathjax.md
#    - Meta tags: reference/meta-tags.md
#    - Variables: reference/variables.md
  - Computing Pipeline:
    - Material for MkDocs: changelog.md
    - Material for MkDocs Insiders: changelog/insiders.md
    - Further Reading:
      - Upgrading: upgrading.md
      - Deprecations: deprecations.md

# Google Analytics
# google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto
